server:
  port: 8081

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://unisthdw003:8761/eureka
